name: Maven Build on Commit

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run Maven Tests
      run: mvn clean package -DskipTests

  package:
    runs-on: ubuntu-latest

    needs: test

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Maven Build
      run: mvn clean package -DskipTests

    - name: Archive production artifacts
       uses: actions/upload-artifact@v2
       with:
         name: packaged-artifact
         path: target/*.jar

